#!/usr/bin/env python3
"""make_tables.py -- write paper/tables/*.tex from the CSVs in data/. Every cell of every generated
table is read from a file named in data/MANIFEST.md; nothing is typed. Two tables are prose and are
kept as static files in paper/tables/ (T2_related.tex, H_prereg.tex): this script does not touch them.

    python3 reproduce/tables.py
"""
import csv, math, pathlib
from collections import OrderedDict

HERE = pathlib.Path(__file__).resolve().parent
DATA = HERE / "data"; TAB = HERE / "out" / "tables"
ORDER = ["tabfm", "tabpfn3", "tabiclv2", "tabpfn26", "tabpfn25", "tabpfn25b", "PFN-v2", "tabicl", "exaone", "tabldm", "mitra@v2",
         "mitra", "tabpfn", "catboost", "lightgbm", "xgboost", "tabm", "ftt", "resnet", "mlp", "LogReg", "knn"]
LABEL = {"knn": "$k$NN", "LogReg": "LogReg", "tabm": "TabM", "mlp": "MLP", "PFN-v2": "TabPFN v2", "tabicl": "TabICL v1", "mitra": "Mitra",
         "tabpfn": "TabPFN v1", "lightgbm": "LightGBM", "catboost": "CatBoost", "xgboost": "XGBoost", "tabiclv2": "TabICL v2",
         "tabpfn3": "TabPFN 3", "ftt": "FT-Transformer", "resnet": "ResNet", "tabpfn25": "TabPFN 2.5", "tabpfn25b": "TabPFN 2.5 (syn.)",
         "tabpfn26": "TabPFN 2.6", "mitra@v2": "Mitra 2", "tabldm": "TabLDM", "tabfm": "TabFM", "exaone": "EXAONE"}
FAMNAME = {"TFM": "foundation models", "GBDT": "gradient-boosted trees", "deep": "deep networks", "classic": "classical"}
FAMORDER = ["TFM", "GBDT", "deep", "classic"]


def rows(name):
    p = DATA / name
    if not p.exists():
        return []
    with p.open() as fh:
        return list(csv.DictReader(fh))


def F(x):
    try:
        return float(x)
    except Exception:
        return float("nan")


def f3(x): return "--" if math.isnan(F(x)) else f"{F(x):.3f}"
def f4(x): return "--" if math.isnan(F(x)) else f"{F(x):.4f}"
def s4(x): return "--" if math.isnan(F(x)) else f"${F(x):+.4f}$"
def f2(x): return "--" if math.isnan(F(x)) else f"{F(x):.2f}"
def pc(x, nd=1): return "--" if math.isnan(F(x)) else f"{100 * F(x):.{nd}f}"
def ci(lo, hi, nd=4): return f"$[{F(lo):+.{nd}f}, {F(hi):+.{nd}f}]$"
def wlt(r, w="pos", l="neg", t="zero"): return f"{int(F(r[w]))}\\,/\\,{int(F(r[l]))}\\,/\\,{int(F(r[t]))}"
def pv(p):
    p = F(p)
    if math.isnan(p): return "--"
    if p >= 0.01: return f"{p:.2f}"
    e = int(math.floor(math.log10(p))); m = p / 10 ** e
    if round(m) >= 10: m, e = 1, e + 1
    return f"${m:.0f} \\times 10^{{{e}}}$"
def tex(s): return str(s).replace("_", "\\_").replace("&", "\\&").replace("%", "\\%")


WIDE = {"T2_related.tex", "T3_models.tex", "T7_labelfree.tex", "T8_options.tex", "A_conference.tex", "B_dk10.tex", "D_mde.tex", "E_certificate.tex", "F_interventions.tex", "T4_main.tex", "B_d29.tex", "T5_levels.tex", "G_synthetic.tex"}


def write(name, body):
    if name in WIDE:
        body = body.replace("\\begin{tabular}", "\\resizebox{\\linewidth}{!}{\\begin{tabular}", 1).replace("\\end{tabular}", "\\end{tabular}}", 1)
    (TAB / name).write_text("% GENERATED by reproduce/tables.py -- do not edit; every cell comes from data/\n" + body)


def by_family(rs, key="family"):
    d = OrderedDict((f, []) for f in FAMORDER)
    for r in rs:
        d.setdefault(r[key], []).append(r)
    return d


# ---- T3 models --------------------------------------------------------------------------------
def t3():
    rs = {r["model"]: r for r in rows("models.csv")}
    out = ["\\begin{table}[tp]", "\\centering", "\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
           "\\caption{The models evaluated. The foundation models run untuned with vendor defaults and condition on the training split as in-context data; "
           "the tuned models run 25 trials of a tree-structured Parzen estimator on a 75/25 split of the training data with validation accuracy as objective, "
           "and the deep models hold out 15\\,\\% of their training split for early stopping. Context cap and softmax temperature are given where the run logs record them "
           "(n.r.: not recorded); the class ceiling is the largest number of classes the model accepts. Citations: see Section~\\ref{sec:tabsets:models}.}",
           "\\label{tab:models}", "\\begin{tabular}{llllll}", "\\toprule",
           "model & package / version & checkpoint & tuning & context cap & temp.\\ / class cap \\\\", "\\midrule"]
    fam_of = {m: rs[m]["family"] for m in ORDER if m in rs}
    last = None
    for m in ORDER:
        if m not in rs: continue
        r = rs[m]
        if r["family"] != last:
            out.append(f"\\multicolumn{{6}}{{l}}{{\\emph{{{FAMNAME[r['family']]}}}}} \\\\")
            last = r["family"]
        tc = f"{tex(r['temperature'])} / {tex(r['class_ceiling'])}" if r["family"] == "TFM" else "--"
        out.append(f"{tex(r['display'])} & {tex(r['package_version'])} & {tex(r['checkpoint'])} & {tex(r['tuning'])} & {tex(r['context_cap'])} & {tc} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("T3_models.tex", "\n".join(out) + "\n")


# ---- T4 main table ------------------------------------------------------------------------------
def main_table(models_file, families_file, label, caption, name):
    ms = {r["model"]: r for r in rows(models_file)}; fams = {r["family"]: r for r in rows(families_file)}
    if not ms: return
    out = ["\\begin{table}[tp]", "\\centering", "\\scriptsize", "\\setlength{\\tabcolsep}{3pt}", f"\\caption{{{caption}}}", f"\\label{{{label}}}",
           "\\begin{tabular}{lcccccc}", "\\toprule",
           "model & AUC & coverage & width & commitment & \\textcolor{gray}{SSCS} & SSCS$^{+}$ \\\\", "\\midrule"]
    last = None
    for m in ORDER:
        if m not in ms: continue
        r = ms[m]
        if r["family"] != last:
            out.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{FAMNAME[r['family']]}}}}} \\\\"); last = r["family"]
        out.append(f"{LABEL[m]} & {f3(r['auc'])} {{\\tiny$[{F(r['auc_lo']):.3f}, {F(r['auc_hi']):.3f}]$}} & {f3(r['cov'])} & {f2(r['width'])} & "
                   f"{f4(r['commit_pt'])} & \\textcolor{{gray}}{{{f3(r['sscs'])}}} & {f3(r['sscsp'])} {{\\tiny$[{F(r['sscsp_lo']):.3f}, {F(r['sscsp_hi']):.3f}]$}} \\\\")
    out.append("\\midrule")
    for f in FAMORDER:
        if f in fams:
            r = fams[f]
            out.append(f"\\emph{{{FAMNAME[f]}, mean}} & {f3(r['auc'])} & {f3(r['cov'])} & {f2(r['width'])} & {f4(r['commit_pt'])} & \\textcolor{{gray}}{{{f3(r['sscs'])}}} & {f3(r['sscsp'])} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write(name, "\n".join(out) + "\n")


# ---- T5 levels ----------------------------------------------------------------------------------
def t5():
    rs = [r for r in rows("N2_eps_contrast_by_level.csv") if r["contrast"] == "TFM-GBDT"]
    if not rs: return
    out = ["\\begin{table}[tp]", "\\centering", "\\footnotesize", "\\setlength{\\tabcolsep}{4pt}",
           "\\caption{Family contrast of the empty-set rate by level and score: foundation models minus gradient-boosted trees, paired over the datasets of the "
           "main block, with the 95\\,\\% bootstrap interval, the Wilcoxon $p$ on the non-zero differences, wins, losses and ties, and the number of datasets "
           "with a non-zero paired difference. A positive value means the foundation models abstain more.}",
           "\\label{tab:levels}", "\\begin{tabular}{llccccc}", "\\toprule", "score & level & mean & 95\\,\\% CI & $p$ & W\\,/\\,L\\,/\\,T & effective $n$ \\\\", "\\midrule"]
    for sc, nm in (("lac", "least ambiguous"), ("apsr", "randomised adaptive")):
        first = True
        for r in sorted([x for x in rs if x["score"] == sc], key=lambda x: F(x["alpha"])):
            out.append(f"{nm if first else ''} & {F(r['alpha']):.2f} & {s4(r['mean'])} & {ci(r['lo'], r['hi'])} & {pv(r['wilcoxon_p'])} & {wlt(r)} & {int(F(r['n_effective']))} of {int(F(r['n']))} \\\\")
            first = False
        out.append("\\midrule")
    out[-1] = "\\bottomrule"
    out += ["\\end{tabular}", "\\end{table}"]
    write("T5_levels.tex", "\n".join(out) + "\n")


# ---- T7 label-free --------------------------------------------------------------------------------
def t7():
    p1f = {r["family"]: r for r in rows("P01_family_table_F1_a10.csv")}; p1m = {r["model"]: r for r in rows("P01_model_table_F1_a10.csv")}
    p2f = {r["family"]: r for r in rows("P02_family_table_F1_a10.csv")}; p2m = {r["model"]: r for r in rows("P02_model_table_F1_a10.csv")}
    p3f = {r["family"]: r for r in rows("P03_family_table_F1_a10.csv")}; p3m = {r["model"]: r for r in rows("P03_model_table_F1_a10.csv")}
    tmp = {r["family"]: r for r in rows("P01_temperature_F1_a10.csv")}
    if not p1f: return
    def line(name, a, b, c, t):
        return (f"{name} & {f4(a['lf_coverr'])} & {f4(a['lftr_coverr'])} & {pc(a['pass_lf_plain'])} & {pc(a['pass_lac_plain'])} & "
                f"{f2(a['lf_width'])} / {f2(a['lf_width_fb'])} & {f2(a['lac_width_fb'])} & {f3(a['lf_eps'])} / {f3(a['lac_eps'])} & "
                f"{f4(b['const_coverr_apsr']) if b else '--'} & {f4(c['apsmapie_absR']) if c else '--'} & {f4(t['lf_coverr_afterT']) if t else '--'} \\\\")
    out = ["\\begin{table}[tp]", "\\centering", "\\scriptsize", "\\setlength{\\tabcolsep}{2.5pt}",
           "\\caption{Three label-free functionals by family, with the named exceptions. Coverage error is $|\\mathrm{cov} - 0.9|$ of the label-free set with the "
           "threshold solved on the calibration probabilities (cal) or on the unlabelled test probabilities (transductive); pass shares are the share of runs holding "
           "the level within the decidable band, for the label-free set and for split conformal on the same runs; widths are raw / fallback for the label-free set and "
           "fallback for split conformal; $\\varepsilon$ is the empty-set rate of the label-free / conformal set; the constant threshold is $1 - \\alpha$ under fully "
           "randomised adaptive sets; $|R|$ is the contained-mass residual under the stored adaptive score; the last column is the label-free coverage error after a "
           "held-out global temperature. Main block, level 0.10; family rows are means of model means.}",
           "\\label{tab:labelfree}", "\\begin{tabular}{lcccccccccc}", "\\toprule",
           " & \\multicolumn{2}{c}{cov.\\ error} & \\multicolumn{2}{c}{pass share (\\%)} & \\multicolumn{2}{c}{width} & & const. & & after \\\\",
           "family or model & cal & transd. & label-free & conformal & label-free & conf. & $\\varepsilon$ lf / conf. & thr.\\ error & $|R|$ & temp. \\\\", "\\midrule"]
    for f in FAMORDER:
        if f in p1f:
            out.append(line(FAMNAME[f], p1f[f], p2f.get(f), p3f.get(f), tmp.get(f)))
    out.append("\\midrule")
    for m in ["LogReg", "knn", "tabpfn", "tabm"]:
        if m in p1m:
            out.append(line(LABEL[m], p1m[m], p2m.get(m), p3m.get(m), tmp.get(m)))
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("T7_labelfree.tex", "\n".join(out) + "\n")


# ---- T8 arms ------------------------------------------------------------------------------------
def t8():
    rs = rows("N2_arms.csv")
    if not rs: return
    name = {"lac": "least ambiguous score", "apsr": "fully randomised adaptive score", "apsd": "deterministic adaptive score",
            "lac_top1": "least ambiguous with top-class fallback", "lac_top1_retuned": "fallback re-tuned to the target"}
    out = ["\\begin{table}[tp]", "\\centering", "\\footnotesize", "\\setlength{\\tabcolsep}{4pt}",
           "\\caption{What each option delivers at a requested level of 0.90 on the main block: delivered coverage, empty-set rate, width raw and under the "
           "fallback accounting, and confidence on committed cases, as the unweighted mean of the four family means, then the delivered coverage of the "
           "foundation models and the trees. The re-tuned row is computed on the runs where the target is reachable.}",
           "\\label{tab:options}", "\\begin{tabular}{lcccccccc}", "\\toprule",
           "option & coverage & $\\varepsilon$ & width & width (fb) & SSCS$^{+}$ & runs & cov.\\ TFM & cov.\\ GBDT \\\\", "\\midrule"]
    for arm in ["lac", "apsr", "apsd", "lac_top1", "lac_top1_retuned"]:
        a = next((r for r in rs if r["arm"] == arm and r["family"] == "all"), None)
        t = next((r for r in rs if r["arm"] == arm and r["family"] == "TFM"), None); g = next((r for r in rs if r["arm"] == arm and r["family"] == "GBDT"), None)
        if a:
            out.append(f"{name[arm]} & {f3(a['delivered_cov'])} & {f3(a['eps'])} & {f2(a['width'])} & {f2(a['width_fb'])} & {f3(a['sscsp'])} & {int(F(a['n_runs'])):,} & "
                       f"{f3(t['delivered_cov']) if t else '--'} & {f3(g['delivered_cov']) if g else '--'} \\\\".replace(",", "{,}", 1) if False else
                       f"{name[arm]} & {f3(a['delivered_cov'])} & {f3(a['eps'])} & {f2(a['width'])} & {f2(a['width_fb'])} & {f3(a['sscsp'])} & {int(F(a['n_runs']))} & "
                       f"{f3(t['delivered_cov']) if t else '--'} & {f3(g['delivered_cov']) if g else '--'} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("T8_options.tex", "\n".join(out) + "\n")


# ---- Appendix A -----------------------------------------------------------------------------------
def a_conf():
    rs = rows("A_conference.csv")
    if not rs: return
    out = ["\\begin{table}[tp]", "\\centering", "\\small",
           "\\caption{The conference results table as published, its reconstruction on the 15-model grid of the earlier campaign, and the same models on the "
           "main block of TabSets; AUC and SSCS, least ambiguous score at level 0.10, cell-then-dataset means.}", "\\label{tab:conference}",
           "\\begin{tabular}{lcccccc}", "\\toprule", " & \\multicolumn{3}{c}{AUC} & \\multicolumn{3}{c}{SSCS} \\\\",
           "model & conference & 15-model grid & TabSets & conference & 15-model grid & TabSets \\\\", "\\midrule"]
    last = None
    for r in sorted(rs, key=lambda x: ORDER.index(x["model"])):
        if r["family"] != last:
            out.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{FAMNAME[r['family']]}}}}} \\\\"); last = r["family"]
        out.append(f"{LABEL[r['model']]} & {f3(r['conf_auc'])} & {f3(r['g_auc'])} & {f3(r['f1_auc'])} & {f3(r['conf_sscs'])} & {f3(r['g_sscs'])} & {f3(r['f1_sscs'])} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("A_conference.tex", "\n".join(out) + "\n")


# ---- Appendix B -----------------------------------------------------------------------------------
def b_dk10():
    rs = rows("P01_DK10_by_cell.csv")
    if not rs: return
    ds = sorted(set(r["dataset"] for r in rs)); ms = [m for m in ORDER if any(r["model"] == m for r in rs)]
    out = ["\\begin{table}[tp]", "\\centering", "\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
           "\\caption{The many-class block: transductive label-free coverage error $|\\mathrm{cov} - 0.9|$ per dataset and model, level 0.10, ten seeds; the "
           "five datasets do not carry a family contrast and are reported one by one.}", "\\label{tab:dk10}",
           "\\begin{tabular}{l" + "c" * len(ms) + "}", "\\toprule", "dataset & " + " & ".join(LABEL[m] for m in ms) + " \\\\", "\\midrule"]
    for d in ds:
        vals = {r["model"]: r["lftr_coverr"] for r in rs if r["dataset"] == d}
        out.append(tex(d) + " & " + " & ".join(f4(vals.get(m, "nan")) for m in ms) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("B_dk10.tex", "\n".join(out) + "\n")


def b_perdataset():
    rs = rows("perdataset_F1.csv")
    if not rs: return
    out = ["\\tiny", "\\setlength{\\tabcolsep}{2.5pt}", "\\begin{longtable}{p{0.30\\linewidth}rrcccccc}",
           "\\caption{Per-dataset family means on the main block, least ambiguous score at level 0.10, ten seeds: AUC, commitment and confidence on committed cases "
           "for the foundation models and the gradient-boosted trees; $n$ is the number of rows and $K$ the number of classes.}\\label{tab:perdataset} \\\\",
           "\\toprule dataset & $n$ & $K$ & AUC TFM & AUC GBDT & commit.\\ TFM & commit.\\ GBDT & SSCS$^{+}$ TFM & SSCS$^{+}$ GBDT \\\\ \\midrule \\endfirsthead",
           "\\toprule dataset & $n$ & $K$ & AUC TFM & AUC GBDT & commit.\\ TFM & commit.\\ GBDT & SSCS$^{+}$ TFM & SSCS$^{+}$ GBDT \\\\ \\midrule \\endhead",
           "\\bottomrule \\endfoot"]
    for r in sorted(rs, key=lambda x: x["dataset"].lower()):
        n = r.get("n", ""); k = r.get("K", "")
        n = f"{int(F(n)):,}".replace(",", "{,}") if n not in ("", None) and not math.isnan(F(n)) else "--"
        k = f"{int(F(k))}" if k not in ("", None) and not math.isnan(F(k)) else "--"
        nm = r["dataset"] if len(r["dataset"]) <= 40 else r["dataset"][:38] + "..."
        d = tex(nm).replace("\\_", "\\_\\allowbreak{}").replace("-", "-\\allowbreak{}")
        out.append(f"{d} & {n} & {k} & {f3(r['auc_TFM'])} & {f3(r['auc_GBDT'])} & {f4(r['commit_pt_TFM'])} & {f4(r['commit_pt_GBDT'])} & {f3(r['sscsp_TFM'])} & {f3(r['sscsp_GBDT'])} \\\\")
    out += ["\\end{longtable}", "\\normalsize"]
    write("B_perdataset.tex", "\n".join(out) + "\n")


# ---- Appendix D -----------------------------------------------------------------------------------
def d_strict():
    rs = rows("strict_contrasts_F1.csv")
    if not rs: return
    nm = {"auc": "AUC", "sscs": "SSCS", "commit_pt": "commitment", "sscsp": "SSCS$^{+}$"}
    out = ["\\begin{table}[tp]", "\\centering", "\\footnotesize",
           "\\caption{The headline contrasts (foundation models minus gradient-boosted trees, least ambiguous score, level 0.10) with the dataset as unit and with "
           "near-duplicate datasets collapsed into strict source units.}", "\\label{tab:strict}", "\\begin{tabular}{llcccc}", "\\toprule",
           "metric & unit & $n$ & mean & 95\\,\\% CI & W\\,/\\,L\\,/\\,T \\\\", "\\midrule"]
    for r in rs:
        out.append(f"{nm[r['metric']]} & {r['units']} & {int(F(r['n']))} & {s4(r['mean'])} & {ci(r['ci_lo'], r['ci_hi'])} & {wlt(r, 'W', 'L', 'T')} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("D_strict.tex", "\n".join(out) + "\n")


def d_agg():
    rs = rows("aggregation_check_F1.csv")
    if not rs: return
    nm = {"sscs": "SSCS", "commit_pt": "commitment", "sscsp": "SSCS$^{+}$"}; ag = {"raw": "raw mean", "z": "$z$-score within dataset", "minmax": "min-max within dataset", "rank": "rank within dataset"}
    out = ["\\begin{table}[tp]", "\\centering", "\\footnotesize",
           "\\caption{The aggregation check: for the composite and its two parts, the family difference (foundation models minus trees) and the rank correlation "
           "with AUC over the 22 model means, under four aggregations of the per-dataset values. The composite changes sign or vanishes under three of the four; "
           "its two parts keep their sign under all four.}", "\\label{tab:aggregation}", "\\begin{tabular}{llcc}", "\\toprule",
           "aggregation & metric & TFM $-$ GBDT & $\\rho$(AUC, metric) \\\\", "\\midrule"]
    for a in ["raw", "z", "minmax", "rank"]:
        for m in ["sscs", "commit_pt", "sscsp"]:
            r = next((x for x in rs if x["aggregation"] == a and x["metric"] == m), None)
            if r:
                out.append(f"{ag[a] if m == 'sscs' else ''} & {nm[m]} & ${F(r['tfm_minus_gbdt']):+.4f}$ & ${F(r['rho_all']):+.2f}$ \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("D_aggregation.tex", "\n".join(out) + "\n")


def d_mde():
    rs = rows("P17_mde_card.csv")
    if not rs: return
    out = ["\\begin{table}[tp]", "\\centering", "\\footnotesize", "\\setlength{\\tabcolsep}{4pt}",
           "\\caption{Minimum detectable effect of the family contrast (foundation models minus trees) on strict source units at a power of 0.80, for a study "
           "of $D$ units, with the effect observed on the main block and the number of units at which that observed effect is detected with the same power.}",
           "\\label{tab:mde}", "\\begin{tabular}{llcccccc}", "\\toprule", "metric & level & observed & $D = 10$ & $D = 20$ & $D = 30$ & $D = 50$ & units for 80\\,\\% \\\\", "\\midrule"]
    for r in rs:
        u = r.get("D_at_power80", "")
        u = "--" if u in ("", None) or math.isnan(F(u)) else f"{F(u):.0f}"
        out.append(f"{tex(r['metric'])} & {tex(r['alpha_s'])} & {s4(r['observed_gap'])} & {f4(r['10'])} & {f4(r['20'])} & {f4(r['30'])} & {f4(r['50'])} & {u} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("D_mde.tex", "\n".join(out) + "\n")


# ---- Appendix E -----------------------------------------------------------------------------------
def e_cert():
    rs = rows("P16_certificate.csv"); ar = {r["model"]: r for r in rows("P16_apsrand_models_all.csv")}
    if not rs: return
    def get(m, sc, al):
        return next((x for x in rs if x["model"] == m and x["score"] == sc and abs(F(x["alpha"]) - al) < 1e-9 and x["block"] == "all"), None)
    def cell(x):
        if not x: return "--"
        v = {"CERTIFIED": "", "documented deviation": "$^{\\dagger}$", "FALSIFIER FIRES": "$^{\\ast}$"}.get(x["verdict"], "")
        return f"${F(x['mean_residual']):+.4f}${v}"
    out = ["\\begin{table}[tp]", "\\centering", "\\scriptsize", "\\setlength{\\tabcolsep}{3pt}",
           "\\caption{The level certificate: mean coverage residual against the enforced level per model and score over every run of the cache. A blank mark is a "
           "certified model, $\\dagger$ a documented deviation, $\\ast$ a residual whose interval excludes zero. The stored adaptive score over-covers for every "
           "model; the fully randomised form (last column) does not, except for $k$NN, whose residual is a tie effect.}", "\\label{tab:certificate}",
           "\\begin{tabular}{lcccccc}", "\\toprule", "model & LAC 0.05 & LAC 0.10 & LAC 0.20 & stored APS 0.10 & rand.\\ APS 0.10 & datasets \\\\", "\\midrule"]
    last = None
    for m in ORDER:
        x10 = get(m, "LAC", 0.1)
        if not x10: continue
        if x10["family"] != last:
            out.append(f"\\multicolumn{{7}}{{l}}{{\\emph{{{FAMNAME[x10['family']]}}}}} \\\\"); last = x10["family"]
        ra = ar.get(m); rav = f"${F(ra['R_apsrand']):+.4f}$" if ra else "--"
        out.append(f"{LABEL[m]} & {cell(get(m, 'LAC', 0.05))} & {cell(x10)} & {cell(get(m, 'LAC', 0.2))} & {cell(get(m, 'APS', 0.1))} & {rav} & {x10['n_datasets']} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("E_certificate.tex", "\n".join(out) + "\n")


# ---- Appendix F -----------------------------------------------------------------------------------
def f_int():
    rs = rows("G_interventions.csv")
    if not rs: return
    out = ["\\begin{table}[tp]", "\\centering", "\\footnotesize", "\\setlength{\\tabcolsep}{4pt}",
           "\\caption{Interventions on the 15-model grid of the earlier campaign, each compared with its own base runs inside that grid; least ambiguous score, level 0.10.}",
           "\\label{tab:interventions}", "\\begin{tabular}{lllrcc}", "\\toprule", "test & model & statistic & $n$ & value & $p$ \\\\", "\\midrule"]
    for r in rs:
        v = F(r["value"]); val = f"{int(v):,}".replace(",", "{,}") if v > 100 else (f"${v:+.4f}$" if abs(v) < 1 else f"{v:.2g}")
        out.append(f"{tex(r['test'])} & {tex(r['model'])} & {tex(r['statistic'])} & {int(F(r['n'])):,} & {val} & {pv(r['p'])} \\\\".replace(",", "{,}"))
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    body = "\n".join(out) + "\n"
    body = body.replace("{,} ", ", ").replace("\\\\{,}", "\\\\")
    write("F_interventions.tex", body)


# ---- Appendix G -----------------------------------------------------------------------------------
def g_syn():
    fams = {r["family"]: r for r in rows("N3_C39_families.csv")}; con = [r for r in rows("N3_C39_contrasts.csv") if r["contrast"] == "TFM-GBDT"]
    if not fams: return
    nm = {"auc": "AUC", "sscs": "SSCS", "commit_pt": "commitment", "sscsp": "SSCS$^{+}$", "cov": "coverage", "width": "width"}
    out = ["\\begin{table}[tp]", "\\centering", "\\footnotesize",
           "\\caption{The synthetic block: family means and the foundation-model minus tree contrast on the synthetic datasets on which every model completed ten "
           "seeds, least ambiguous score, level 0.10. Kept apart from every headline contrast.}", "\\label{tab:synthetic}", "\\begin{tabular}{lcccccc}", "\\toprule",
           "family & AUC & coverage & width & commitment & SSCS & SSCS$^{+}$ \\\\", "\\midrule"]
    for f in FAMORDER:
        if f in fams:
            r = fams[f]; out.append(f"{FAMNAME[f]} & {f3(r['auc'])} & {f3(r['cov'])} & {f2(r['width'])} & {f4(r['commit_pt'])} & {f3(r['sscs'])} & {f3(r['sscsp'])} \\\\")
    out += ["\\midrule", "\\multicolumn{7}{l}{\\emph{contrast, foundation models minus trees: mean, 95\\,\\% CI, $p$, W\\,/\\,L\\,/\\,T}} \\\\"]
    for r in con:
        if r["metric"] in nm:
            out.append(f"{nm[r['metric']]} & \\multicolumn{{6}}{{l}}{{{s4(r['mean'])}, {ci(r['lo'], r['hi'])}, $p = $ {pv(r['wilcoxon_p'])}, {wlt(r)}}} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("G_synthetic.tex", "\n".join(out) + "\n")


def d_vovk():
    rs = rows("P20_vovk_rho.csv")
    if not rs: return
    from scipy import stats as _st
    tfm = [r for r in rs if r["model"] in ORDER[:13]]
    out = ["\\begin{table}[tp]", "\\centering", "\\footnotesize",
           "\\caption{The ten efficiency criteria of Vovk et al.\\ on the main block: family means of model means, and the Spearman rank "
           "correlation of each criterion with accuracy across the 13 foundation models, with its $p$-value. Lower is better for every criterion.}",
           "\\label{tab:vovk}", "\\begin{tabular}{lcccccc}", "\\toprule", "criterion & TFM & GBDT & deep & classical & $\\rho$ within TFMs & $p$ \\\\", "\\midrule"]
    fam_of = {m: f for f in FAMORDER for m in ORDER if (m in ORDER[:13] and f == "TFM") or (m in ("catboost", "lightgbm", "xgboost") and f == "GBDT") or (m in ("tabm", "ftt", "resnet", "mlp") and f == "deep") or (m in ("LogReg", "knn") and f == "classic")}
    for c in ["S", "N", "U", "F", "M", "E", "OU", "OF", "OM", "OE"]:
        means = {}
        for f in FAMORDER:
            vals = [F(r[c]) for r in rs if fam_of.get(r["model"]) == f]
            means[f] = sum(vals) / len(vals) if vals else float("nan")
        rr = _st.spearmanr([F(r[c]) for r in tfm], [F(r["accuracy"]) for r in tfm])
        out.append(f"{c} & {f3(means['TFM'])} & {f3(means['GBDT'])} & {f3(means['deep'])} & {f3(means['classic'])} & ${rr.statistic:+.2f}$ & {pv(rr.pvalue)} \\\\")
    out += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    write("D_vovk.tex", "\n".join(out) + "\n")


def h_prereg():
    """The analysis plan: the twenty analyses specified before the cache was read.

    The article promises this with the data, so it is generated from a released table
    rather than written by hand in the manuscript, where the release could not keep it
    in step.
    """
    rs = rows("prereg.csv")
    out = [r"\begin{table}[tp]", r"\centering", r"\scriptsize",
           r"\setlength{\tabcolsep}{3pt}",
           r"\caption{The twenty analyses specified in advance on the probability cache, "
           r"with the outcome of each and where it enters the article.}",
           r"\label{tab:prereg}",
           r"\begin{tabular}{p{0.05\linewidth}p{0.42\linewidth}p{0.14\linewidth}p{0.33\linewidth}}",
           r"\toprule",
           r" & hypothesis & outcome & what it bounds, or where it is used \\",
           r"\midrule"]
    for r in rs:
        out.append(f"{r['n']} & {r['hypothesis']} & {r['outcome']} & {r['where']} \\\\")
    out += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write("H_prereg.tex", "\n".join(out) + "\n")


def main():
    TAB.mkdir(parents=True, exist_ok=True)
    d_vovk()
    t3()
    main_table("models_F1.csv", "families_F1.csv", "tab:main",
               "The main table: each model on the main block under the least ambiguous score at level 0.10, cell-then-dataset means over ten seeds, with combined "
               "95\\,\\% bootstrap intervals over datasets for AUC and confidence on committed cases. SSCS is printed in grey between the two quantities whose product it is.",
               "T4_main.tex")
    main_table("N3_D29_models.csv", "N3_D29_families.csv", "tab:d29",
               "The large-dataset block: the models complete on the new real datasets outside the conference envelope, same conventions as Table~\\ref{tab:main}.",
               "B_d29.tex")
    h_prereg(); t5(); t7(); t8(); a_conf(); b_dk10(); b_perdataset(); d_strict(); d_agg(); d_mde(); e_cert(); f_int(); g_syn()
    print("tables written:", sorted(p.name for p in TAB.glob("*.tex")))


if __name__ == "__main__":
    main()
